name: CI

on:
  push:
    branches:
      - main

jobs:
  test-cypress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ci-test-project
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Configure SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Configure Git
      run: |
        git config --global user.email "${{ secrets.USER_NAME }}"
        git config --global user.name "${{ secrets.USER_EMAIL }}"

    - name: Clone lecturers-backstage
      run: |
        git clone git@github.com:linche0859/lecturers-backstage.git lecturers-backstage
      env:
        GH_TOKEN: ${{ secrets.CI_TOKEN }}

    - name: Install lecturers-backstage dependencies
      run: |
        cd lecturers-backstage
        npm install

    - name: Create lecturers-backstage .env file
      run: |
        cd lecturers-backstage
        echo API_URL=${{ secrets.LECTURERS_BACKSTAGE_API_URL }} >> .env
        echo LECTURER_DOMAIN=${{ secrets.LECTURERS_BACKSTAGE_LECTURER_DOMAIN }} >> .env
        echo OFFICIAL_DOMAIN=${{ secrets.LECTURERS_BACKSTAGE_OFFICIAL_DOMAIN }} >> .env
        echo APP_URL=${{ secrets.LECTURERS_BACKSTAGE_APP_URL }} >> .env
        echo APP_AWS_THUMBNAIL_URL=${{ secrets.LECTURERS_BACKSTAGE_APP_AWS_THUMBNAIL_URL }} >> .env
        echo APP_AWS_BUCKET=${{ secrets.LECTURERS_BACKSTAGE_APP_AWS_BUCKET }} >> .env
        echo COOKIES_DOMAIN=${{ secrets.LECTURERS_BACKSTAGE_COOKIES_DOMAIN }} >> .env
        echo CROSS_DOMAIN=${{ secrets.LECTURERS_BACKSTAGE_CROSS_DOMAIN }} >> .env
        echo ENABLE_LOCALE=${{ secrets.LECTURERS_BACKSTAGE_ENABLE_LOCALE }} >> .env
        echo LOCALE_URL=${{ secrets.LECTURERS_BACKSTAGE_LOCALE_URL }} >> .env
        echo LOCALE_TOKEN=${{ secrets.LECTURERS_BACKSTAGE_LOCALE_TOKEN }} >> .env
        echo ENABLE_PHRASE=${{ secrets.LECTURERS_BACKSTAGE_ENABLE_PHRASE }} >> .env

    - name: Run lecturers-backstage
      run: |
        cd lecturers-backstage
        npx nuxt -p 3001

    - name: Clone cypress-e2e
      run: |
        git clone git@github.com:linche0859/cypress-e2e.git cypress-e2e
      env:
        GH_TOKEN: ${{ secrets.CI_TOKEN }}
      
    - name: Install cypress-e2e dependencies
      run: |
        cd cypress-e2e
        npm install

    - name: Create cypress-e2e .env file
      run: |
        cd cypress-e2e
        echo PROJECT_ID=${{ secrets.CYPRESS_E2E_PROJECT_ID }} >> .env
        echo SPA_URL=${{ secrets.CYPRESS_E2E_SPA_URL }} >> .env
        echo BASE_URL=${{ secrets.CYPRESS_E2E_BASE_URL }} >> .env
        echo VIEWPORT_WIDTH=${{ secrets.CYPRESS_E2E_VIEWPORT_WIDTH }} >> .env
        echo VIEWPORT_HEIGHT=${{ secrets.CYPRESS_E2E_VIEWPORT_HEIGHT }} >> .env
        echo LECTURER_URL=${{ secrets.CYPRESS_E2E_LECTURER_URL }} >> .env
        echo ADMIN_URL=${{ secrets.CYPRESS_E2E_ADMIN_URL }} >> .env

    - name: Cypress tests
      run: |
        cd cypress-e2e
        npm run cy:run

