name: CI

on:
  push:
    branches:
      - main

jobs:
  basic-ubuntu-20:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout ci-test-project
      uses: actions/checkout@v4

    - name: Configure Git
      run: |
        git config --global user.email "${{ secrets.USER_NAME }}"
        git config --global user.name "${{ secrets.USER_EMAIL }}"

    - name: Clone cypress-e2e
      run: |
        git clone https://${{ secrets.CI_TOKEN }}:x-oauth-basic@github.com/linche0859/cypress-e2e.git cypress-e2e
      env:
        GH_TOKEN: ${{ secrets.CI_TOKEN }}
      
    - name: Install dependencies
      run: |
        cd cypress-e2e
        npm install

    - name: Cypress tests
      run: |
        cd cypress-e2e
        npm run cy:run

