name: CI

on:
  push:
    branches:
      - main

jobs:
  basic-ubuntu-20:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout ci-cypress-project
      uses: actions/checkout@v4
      with:
        repository: linche0859/ci-cypress-project
        path: ci-cypress-project

    - name: Install dependencies
      run: |
        cd ci-cypress-project
        npm install

    - name: Cypress tests
      uses: ./
      with:
        working-directory: ./
        build: npx cypress info

