name: CI

on:
  push:
    branches:
      - main

jobs:
  test-cypress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ci-test-project
      uses: actions/checkout@v4

    - name: Configure SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Configure Git
      run: |
        git config --global user.email "${{ secrets.USER_NAME }}"
        git config --global user.name "${{ secrets.USER_EMAIL }}"

    - name: Clone lecturers-backstage
      run: |
        git clone git@github.com:linche0859/lecturers-backstage.git lecturers-backstage
      env:
        GH_TOKEN: ${{ secrets.CI_TOKEN }}

    - name: Install lecturers-backstage dependencies
      run: |
        cd lecturers-backstage
        npm install

    - name: Run lecturers-backstage
      run: |
        cd lecturers-backstage
        npm run dev -p 3001

    - name: Clone cypress-e2e
      run: |
        git clone git@github.com:linche0859/cypress-e2e.git cypress-e2e
      env:
        GH_TOKEN: ${{ secrets.CI_TOKEN }}
      
    - name: Install cypress-e2e dependencies
      run: |
        cd cypress-e2e
        npm install

    - name: Cypress tests
      run: |
        cd cypress-e2e
        npm run cy:run

